local Tabel = {}

Tabel["levelButtonPosition"] = {[1] = {0, 0.36}, 	[2] = {0.21, 0.26},	[3] = {0.2, 0.46}, 	[4] = {0.33, 0.58},
								[5] = {0.5, 0.5},	[6] = {0.55, 0.25},	[7] = {0.72, 0.37},	[8] = {0.9, 0.55},
								[9] = {1.07, 0.46},	[10] = {1, 0.25},	[11] = {1.58, 0.45},[12] = {1.78, 0.42},
								[13] = {1.98, 0.38},[14] = {2.01, 0.63},[15] = {2.23, 0.72},[16] = {2.39, 0.6},
								[17] = {2.35, 0.29},[18] = {2.55, 0.3},	[19] = {2.62, 0.63},[20] = {2.82, 0.68},
								[21] = {3.3, 0.28},	[22] = {3.3, 0.5},	[23] = {3.59, 0.66},[24] = {3.8, 0.58}, 
								[25] = {3.82, 0.37},[26] = {3.95, 0.27},[27] = {4.16, 0.28},[28] = {4.35, 0.32},
								[29] = {4.61,0.4},	[30] = {4.56,0.63},	[31] = {5.15, 0.43},[32] = {5.18,0.2},
								[33] = {5.36, 0.28},[34] = {5.49,0.52},	[35] = {5.67,0.42},	[36] = {5.8, 0.27},
								[37] = {5.92,0.36},	[38] = {6.05,0.47},	[39] = {6.2,0.38},	[40] = {6.17,0.2}
								}
Tabel["achieveItem"] =	{	[1] = {"x5","完成新手关卡"},		[2] = {"x5","英雄完成三次升级"},
							[3] = {"x5","adslhf"},				[4] = {"x5","adslhf"},
							[5] = {"x5","adslhf"},				[6] = {"x5","完成新手关卡"},	
							[7] = {"x5","英雄完成三次升级"},	[8] = {"x5","adslhf"},
							[9] = {"x5","完成新手关卡"},		[10] = {"x5","英雄完成三次升级"},
							[11] = {"x5","adslhf"},				[12] = {"x5","英雄完成三次升级"},
							[13] = {"x5","adslhf"},				[14] = {"x5","adslhf"},
							[15] = {"x5","adslhf"}
							
						}

Tabel["taskItem"] = {	[1] = {"建造一个小炮","使用小炮消灭\n30个怪物","使用英雄消灭5\n个怪物"},
						[2] = {"x5","英雄完成三次升级"},
						[3] = {"x5","adslhf"},
						[4] = {"x5","adslhf"},
						[5] = {"x5","adslhf"},
						[6] = {"x5","完成新手关卡"},
						[7] = {"x5","英雄完成三次升级"},
						[8] = {"x5","adslhf"},
						[9] = {"x5","完成新手关卡"},
						[10] = {"x5","英雄完成三次升级"},
						[11] = {"x5","adslhf"},
						[12] = {"x5","英雄完成三次升级"},
						[13] = {"x5","adslhf"},
						[14] = {"x5","adslhf"},
						[15] = {"x5","adslhf"},
						[16] = {"x5","完成新手关卡"},
						[17] = {"x5","英雄完成三次升级"},
						[18] = {"x5","adslhf"},
						[19] = {"x5","完成新手关卡"},
						[20] = {"x5","英雄完成三次升级"},
						[21] = {"x5","adslhf"},
						[22] = {"x5","英雄完成三次升级"},
						[23] = {"x5","adslhf"},
						[24] = {"x5","adslhf"},
						[25] = {"x5","adslhf"},
						[26] = {"x5","完成新手关卡"},
						[27] = {"x5","英雄完成三次升级"},
						[28] = {"x5","adslhf"},
						[29] = {"x5","完成新手关卡"},
						[30] = {"x5","英雄完成三次升级"},
						[31] = {"x5","adslhf"},
						[32] = {"x5","英雄完成三次升级"},
						[33] = {"x5","adslhf"},
						[34] = {"x5","adslhf"},
						[35] = {"x5","adslhf"},
						[36] = {"x5","完成新手关卡"},
						[37] = {"x5","英雄完成三次升级"},
						[38] = {"x5","adslhf"},
						[39] = {"x5","完成新手关卡"},
						[40] = {"x5","英雄完成三次升级"}					
					}

Tabel["taskItempic"] = {[1] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[2] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[3] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[4] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[5] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[6] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[7] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[8] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[9] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[10] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[11] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[12] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[13] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[14] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[15] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[16] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[17] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[18] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[19] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[20] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[21] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[22] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[23] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[24] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[25] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[26] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[27] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[28] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[29] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[30] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[31] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[32] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[33] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[34] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[35] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[36] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[37] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[38] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[39] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"},
						[40] = {"#taskTowerIcon1.png", "#taskTowerIcon1.png", "#taskHeroIcon1.png"}
						}					

Tabel["weapon"] = {	[1] = {"#T_select_1.png"},
					[2] = {"#T_select_1.png", "#T_select_2.png"},
					[3] = {"#T_select_1.png", "#T_select_2.png", "#T_select_3.png"},
					[4] = {"#T_select_1.png", "#T_select_2.png", "#T_select_16.png","#T_select_3.png"},
					[5] = {"#T_select_1.png","#T_select_2.png", "#T_select_3.png", "#T_select_16.png","#T_select_18.png"},
					[6] = {"#T_select_1.png", "#T_select_2.png"},
					[7] = {"#T_select_1.png", "#T_select_2.png", "#T_select_3.png"},
					[8] = {"#T_select_1.png", "#T_select_3.png", "#T_select_18.png","#T_select_16.png"},
					[9] = {"#T_select_1.png"，"#T_select_2.png", "#T_select_3.png"},
					[10] = {"#T_select_1.png", "#T_select_2.png"},
					[11] = {"#T_select_1.png", "#T_select_2.png", "#T_select_3.png"},
					[12] = {"#T_select_1.png", "#T_select_2.png", "#T_select_3.png","#T_select_16.png"},
					[13] = {"#T_select_1.png"},
					[14] = {"#T_select_1.png", "#T_select_1.png"},
					[15] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[16] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png","#T_select_1.png"},
					[17] = {"#T_select_1.png"},
					[18] = {"#T_select_1.png", "#T_select_1.png"},
					[19] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[20] = {"#T_select_1.png"},
					[21] = {"#T_select_1.png", "#T_select_1.png"},
					[22] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[23] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png","#T_select_1.png"},
					[24] = {"#T_select_1.png"},
					[25] = {"#T_select_1.png", "#T_select_1.png"},
					[26] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[27] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png","#T_select_1.png"},
					[28] = {"#T_select_1.png"},
					[29] = {"#T_select_1.png", "#T_select_1.png"},
					[30] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[31] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png","#T_select_1.png"},
					[32] = {"#T_select_1.png"},
					[33] = {"#T_select_1.png", "#T_select_1.png"},
					[34] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[35] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png","#T_select_1.png"},
					[36] = {"#T_select_1.png"},
					[37] = {"#T_select_1.png", "#T_select_1.png"},
					[38] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png"},
					[39] = {"#T_select_1.png", "#T_select_1.png", "#T_select_1.png","#T_select_1.png"},
					[40] = {"#T_select_1.png"}
				}
Tabel["tackle"] =  {"#pre_itemIcon1.png", "#pre_itemIcon2.png", "#pre_itemIcon3.png","#pre_itemIcon4.png"}
					
Tabel["tackleIntroduction"] = {"关卡初始圣水\n增加500","守护点生命上限\n提高两点","英雄复活时间\n减少一半","英雄技能冷却\n时间减少30%"}

Tabel["tacklePrice"] = {"200", "800", "1200", "2000"}

return Tabel